### ISSUE TITLE
Where can I to look demo of backend?

### ISSUE THREAD

**Issue by typo3ua** [expresspixel/estatezilla#14]
Where can I to look demo of backend the estatezilla?

**Comment by typo3ua** [comment]
Server requirements
Congratulations! Your server meets the requirements for EstateZilla.

You have PHP 5.4.45-0+deb7u11
You have the openssl extension
You have the pdo extension
You have the pdo_mysql extension
You have the mbstring extension
You have the tokenizer extension
Unzipping
Successfully unzipped.
* Remember have mod_rewrite enabled and give permissions to folders (storage and bootstrap/cache)

The admin panel is located here.

The username is "admin" and the password is "changeme". Please change the password when you login.

But I enter like username is "admin" and the password is "changeme" and **get error "Error: Invalid login"**

**What is wrong?**

**Comment by typo3ua** [comment]
I understood what is wrong.
For work need PHP version 7.0 minimum

**Comment by SqualaDesign** [comment]
Server requirements
Congratulations! Your server meets the requirements for EstateZilla.

You have PHP 7.2.1
You have the openssl extension
You have the pdo extension
You have the pdo_mysql extension
You have the mbstring extension
You have the tokenizer extension
Unzipping
open('full.zip') === TRUE) { $zip->extractTo(__DIR__); $zip->close(); @unlink('full.zip'); @unlink('install.php'); echo 'Successfully unzipped.'; @chmod("storage", 0777); @chmod("bootstrap/cache", 0777); } else { echo 'Unable to unzip. Please make sure you have the correct permissions. Please submit an issue on github.'; die(); } ?> 
* Remember have mod_rewrite enabled and give permissions to folders (storage and bootstrap/cache)

The admin panel is located here.

The username is "admin" and the password is "changeme". Please change the password when you login.



**Error: Invalid login**

**Comment by aneeshtan** [comment]
And when the Mcrypt is not active in php 7 you must switch back to 5.6 , which then the script is not working.
